apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  namespace: area
spec:
  storageClassName: "postgres-class"
  capacity:
    storage: 5Gi
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
  namespace: area
spec:
  storageClassName: "postgres-class"
  resources:
    requests:
      storage: 5Gi
  accessModes:
      - ReadWriteOnce