apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: area
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-area
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: backend-secrets
          - secretRef:
              name: postgres-secrets
          - configMapRef:
              name: postgres-config
          image: molaryy35/area-back:latest
          ports:
            - containerPort: 8080
