apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: area
type: Opaque
data:
  JWT_SECRET_KEY: Qmxvb3BlcjkyCg==
  GMAIL_URL: aHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGg/Y2xpZW50X2lkPSVzJnJlZGlyZWN0X3VyaT0lcyZyZXNwb25zZV90eXBlPWNvZGUmc2NvcGU9aHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9nbWFpbC5zZW5kIGh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZ21haWwucmVhZG9ubHkK
  GMAIL_TOKEN: aHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4K
  GMAIL_PROFILE: aHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vZ21haWwvdjEvdXNlcnMvbWUvcHJvZmlsZQo=
  GMAIL_SEND: aHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vZ21haWwvdjEvdXNlcnMvbWUvbWVzc2FnZXMvc2VuZAo=
  OUTLOOK_URL: aHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tLyVzL29hdXRoMi92Mi4wL2F1dGhvcml6ZT9jbGllbnRfaWQ9JXMmcmVzcG9uc2VfdHlwZT1jb2RlJnJlZGlyZWN0X3VyaT0lcyZyZXNwb25zZV9tb2RlPXF1ZXJ5JnNjb3BlPW9wZW5pZCAlcwo=
  OUTLOOK_GRAPH: aHR0cHM6Ly9ncmFwaC5taWNyb3NvZnQuY29tL01haWwuU2VuZCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIFVzZXIuUmVhZAo=
  OUTLOOK_TOKEN: aHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tLyVzL29hdXRoMi92Mi4wL3Rva2VuCg==
  OUTLOOK_PROFILE: aHR0cHM6Ly9ncmFwaC5taWNyb3NvZnQuY29tL3YxLjAvbWUK
  OUTLOOK_SEND: aHR0cHM6Ly9ncmFwaC5taWNyb3NvZnQuY29tL3YxLjAvbWUvc2VuZE1haWwK
  GITHUB_URL: aHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoL2F1dGhvcml6ZT9jbGllbnRfaWQ9JXMmcmVkaXJlY3RfdXJpPSVzJnNjb3BlPXVzZXI6ZW1haWwK
  GITHUB_TOKEN: aHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoL2FjY2Vzc190b2tlbgo=
  GITHUB_PROFILE: aHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS91c2VyL2VtYWlscwo=
  SLACK_URL: aHR0cHM6Ly9zbGFjay5jb20vb2F1dGgvdjIvYXV0aG9yaXplP2NsaWVudF9pZD0lcyZzY29wZT1jaGF0OndyaXRlLHVzZXJzOnJlYWQmcmVkaXJlY3RfdXJpPSVzCg==
  SLACK_TOKEN: aHR0cHM6Ly9zbGFjay5jb20vYXBpL29hdXRoLnYyLmFjY2Vzcwo=
  SLACK_PROFILE: aHR0cHM6Ly9zbGFjay5jb20vYXBpL3VzZXJzLmlkZW50aXR5Cg==
  SLACK_API_URL: aHR0cHM6Ly9zbGFjay5jb20vYXBpCg==
  SLACK_BOT_TOKEN: eG94Yi03ODIwNjkwODM3NzE4LTc5MjA1NTU5OTgwODItemNGYkJUR2NCUllRSXVLSHZFU3ZuZnNRCg==
  SPOTIFY_URL: aHR0cHM6Ly9hY2NvdW50cy5zcG90aWZ5LmNvbS9hdXRob3JpemU/Y2xpZW50X2lkPSVzJnJlc3BvbnNlX3R5cGU9Y29kZSZyZWRpcmVjdF91cmk9JXMmc2NvcGU9dXNlci1yZWFkLWVtYWlsIHVzZXItZm9sbG93LXJlYWQK
  SPOTIFY_TOKEN: aHR0cHM6Ly9hY2NvdW50cy5zcG90aWZ5LmNvbS9hcGkvdG9rZW4K
  SPOTIFY_PROFILE: aHR0cHM6Ly9hcGkuc3BvdGlmeS5jb20vdjEvbWUK
  GITLAB_URL: aHR0cHM6Ly9naXRsYWIuY29tL29hdXRoL2F1dGhvcml6ZT9jbGllbnRfaWQ9JXMmcmVkaXJlY3RfdXJpPSVzJnJlc3BvbnNlX3R5cGU9Y29kZSZzY29wZT1hcGkK
  GITLAB_TOKEN: aHR0cHM6Ly9naXRsYWIuY29tL29hdXRoL3Rva2VuCg==
  GITLAB_PROFILE: aHR0cHM6Ly9naXRsYWIuY29tL2FwaS92NC91c2VyCg==
  TELEGRAM_BOT_TOKEN: NzkwMTg1MDk5MTpBQUZGYUp2RHZURHBkUldBTWdvR1Ytc1pxanBPVlo5MTRrOAo=
  GMAIL_CLIENT_ID: Njk0NzQ5MDI2NDI0LXBiOWJ2dGF2MnRtdmpiaTZxOWFzZ3NpZDA3YjA3c3BnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
  GMAIL_CLIENT_SECRET: R09DU1BYLXVfRmNVSnhOeUtLUkhsNWRwNUFtZ0NhRGtmLW8K
  GMAIL_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL29hdXRoMmNhbGxiYWNrCg==
  FRONTEND_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgxCg==
  NOTION_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL25vdGlvbi9jYWxsYmFjawo=
  MICROSOFT_CLIENT_ID: NDkwYTMyMWMtZjI2OS00NjNlLWI4NjEtMzAzMDY0MmRkYzIyCg==
  MICROSOFT_TENANT_ID: OTAxY2I0Y2EtYjg2Mi00MDI5LTkzMDYtZTVjZDBmNmQ5Zjg2Cg==
  MICROSOFT_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL291dGxvb2svY2FsbGJhY2sK
  DISCORD_CLIENT_ID: MTI4NjAwNTQ1MjAxODAyNDU2Mwo=
  DISCORD_CLIENT_SECRET: SEVNSzRtc2FDS3VRTHN4Q1phOWctbGV2bHg1TGQ3MGoK
  DISCORD_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL2Rpc2NvcmQvY2FsbGJhY2sK
  DISCORD_TOKEN_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvb2F1dGgyL3Rva2VuCg==
  DISCORD_PROFILE_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvdXNlcnMvQG1lCg==
  DISCORD_OAUTH_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9vYXV0aDIvYXV0aG9yaXplP2NsaWVudF9pZD0lcyZwZXJtaXNzaW9ucz02NzU4NCZyZXNwb25zZV90eXBlPWNvZGUmcmVkaXJlY3RfdXJpPSVzJmludGVncmF0aW9uX3R5cGU9MCZzY29wZT1ib3QK
  DISCORD_BOT_TOKEN: TVRJNE5qQXdOVFExTWpBeE9EQXlORFUyTXcuR1VXSU5wLkFtbEtkcDZCaTFfNDFrRUJfOWxPSUJ2TFhNVFIxSml0eV9hUWQwCg==
  DISCORD_API_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkK
  SLACK_CLIENT_ID: NzkxNjQ0NDQ3MzI1MS43OTE2NDg5NjM2NzU1Cg==
  SLACK_CLIENT_SECRET: YWFjYTQzNWNiZjBmZGJiZGU3YWI2YzIxYmRjMGJmNDYK
  SLACK_REDIRECT_URL: aHR0cHM6Ly80MGY4LTE2My01LTIzLTY4Lm5ncm9rLWZyZWUuYXBwL3NsYWNrL2NhbGxiYWNrCg==
  SPOTIFY_CLIENT_ID: NGNmYjE2YjYyYjYxNDRkZjliMjljZjg1MzUxODJkNzEK
  SPOTIFY_CLIENT_SECRET: NDk2Mzg2NjFlYjEzNDM1YTk5Mjc0MjUzNGU3MmU0MDYK
  SPOTIFY_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL3Nwb3RpZnkvY2FsbGJhY2sK
  GITLAB_CLIENT_ID: ODEzZGExZWYwZjMxZDFhOGYzM2IyMDFmZmY2ZDE2ODFiYmFiMjU1M2QxYzQ2MDMzODVjZWFiMGIwNzJlYTA2ZAo=
  GITLAB_CLIENT_SECRET: Z2xvYXMtOWI2MWQ4MzdmZmUyNDc3YjUwNTljOTM3NTU1ODdhM2U2NmM4NzE5YTc3ZDg3M2U4MTZlMGNlZDI3OWViZTBlYQo=
  GITLAB_CLIENT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL2dpdGxhYi9jYWxsYmFjawo=
  TRELLO_CLIENT_ID: U2swdXN4SGhqb2gwZW9Ya2NQMEhjTXpnaVlJdHpkV2kK
  TRELLO_CLIENT_SECRET: QVRPQVVYeW9ZWHVqNjJsM09yNFliM1hKRlZRTE9sWDBrOG91Skg0MkQxRnhwanVscWFVNDVCb1VnWXpTWFJLaWpEcmFDMjg5MUU4NQo=
  TRELLO_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL3RyZWxsby9jYWxsYmFjawo=
  TWITCH_CLIENT_ID: c2d1MTQwcWt2eG4zb201c2FpM2xic25kejR5eW93Cg==
  TWITCH_CLIENT_SECRET: bXo0bTB1bzZkaTNrcm85eHU4dXF1ODQwNjd5a203Cg==
  TWITCH_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL3R3aXRjaC9jYWxsYmFjawo=
