name: Build C++

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened

env:
  # All binaries separated by ' '
  EXECUTABLES: "r-type_client r-type_server"

jobs:
  push:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tchips46/r-type
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup
        run: mkdir ./build/ && cd ./build/ && cmake .. -G "Unix Makefiles" -DTEST_CODE=ON
      - name: Build
        run: cd ./build/ && cmake --build . --config Release
        timeout-minutes: 5
      - name: Check if all files exist
        run: |
          for file in $EXECUTABLES; do
            if test -f "$file"; then
              echo "File $file exists"
            else
              echo "File $file does not exist"
              exit 1
            fi
          done
