name: Build C++

on:
  push:
    branches: [ main, dev ]
  pull_request:
    types:
      - opened
    branches: [ main, dev ]

env:
  # All binaries separated by ' '
  EXECUTABLES: "r-type_client r-type_server"

jobs:
  push:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tchips46/r-type

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup
      run: mkdir ./build/ && cd ./build/ && cmake .. -G "Unix Makefiles" -DTEST_CODE=ON
    - name: Build
      run: cd ./build/ && cmake --build . --config Release && cmake --install .
      timeout-minutes: 5

    - name: Check if all files exist
      run: |
        for file in $EXECUTABLES; do
          if test -f "$file"; then
            echo "File $file exists"
          else
            echo "File $file does not exist"
            exit 1
          fi
        done
