name: deploy documentation

on:
  push:
    branches: [ "main", "master" ]

env:
  USER: molaryy35
  IMAGE: doc-docusaurus
  VERSION: latest

jobs:
  backend-image:
    name: Create documentation image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Check out the repo
      - uses: docker/login-action@v3
        name: Log in to Docker Hub
        with:
          username: ${{ env.USER }}
          password: ${{ secrets.DOCKER_PASSWORD_GIT }}
      - name: "Push the image"
        working-directory: ./docs/docusaurus
        run: |
          docker build --platform linux/amd64 -t ${{ env.USER }}/${{ env.IMAGE }} .
          docker image tag ${{ env.USER }}/${{ env.IMAGE }} ${{ env.USER }}/${{ env.IMAGE }}:${{ env.VERSION }}
