name: Linter C++

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - 'ga-ignore-**'
  push:
    branches-ignore:
      - 'ga-ignore-**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: tchips46/r-type

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Setup
#        run: mkdir ./build/ && cd ./build/ && cmake .. -G "Unix Makefiles" -DTEST_CODE=ON
#      - name: Build
#        run: cd ./build/ && cmake --build . --config Release && cmake --install .
#        timeout-minutes: 5
#
#      - name: Run clang-tidy linter
#        run: |
#          clang-tidy \
#            --fix \
#            --fix-errors \
#            $(find . -name '*.cpp' ! \( -path './asio/*' -o -path './build/*' -o -path './cmake-build-debug/*' \)) \
#            -- -iquote./includes
#
    if: github.event.repository.name != 'B-CPP-500-PAR-5-2-rtype-nicolas.gillard'
