name: r-type-mirror

on:
  push:
    branches: [ "main" ]

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-CPP-500-PAR-5-2-rtype-nicolas.gillard.git

jobs:
  r-type-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout's a repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
