name: area-mirror

on:
  push:
    branches: [ "test" ]

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DEV-500-PAR-5-1-r-type-mohammed.jbilou.git

jobs:
  area-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout's a repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
