name: Push CI/CD

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - 'ga-ignore-**'
  push:
    branches-ignore:
      - 'ga-ignore-**'

env:
  # All binaries separated by ' '
  EXECUTABLES: "r-type_client r-type_server"
  REPO_NAME: B-CPP-500-PAR-5-2-rtype-nicolas.gillard
  MIRROR_URL: git@github.com:EpitechPromo2027/B-CPP-500-PAR-5-2-rtype-nicolas.gillard.git

jobs:
  commits:
    if: github.event.repository.name != 'B-CPP-500-PAR-5-2-rtype-nicolas.gillard'

    name: Checking for Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.2.0

  build:

    name: Build
    runs-on: ubuntu-latest
    container:
      image: tchips46/r-type

    needs: commits

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup
        run: mkdir ./build/ && cd ./build/ && cmake .. -G "Unix Makefiles" -DTEST_CODE=ON
      - name: Build
        run: cd ./build/ && cmake --build . --config Release
        timeout-minutes: 5

      - name: Check if all files exist
        run: |
          for file in $EXECUTABLES; do
            if test -f "$file"; then
              echo "File $file exists"
            else
              echo "File $file does not exist"
              exit 1
            fi
          done

  push_to_mirror:
    name: "Pushing To The Mirror Repository"
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout's a repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
